### PR TITLE
Fix snap to origin

### LINKED ISSUE #31: Grid Snap Not Working?
Hey, love the clean API on this package!

Just having some trouble getting grid-snapping to work.  Can you provide an example, or elucidate what might be wrong with the following code?  I'm not seeing any snap behavior change with or without the grid options provided in the DragOptions object.
image

### PR DESCRIPTION
**Pull request by bluwy**
Fixes #31 

Seems to be introduced in https://github.com/PuruVJ/svelte-drag/commit/291081e4a952e06071266a71c6dfa0088c1d7c96 (first implementation of grid snap).Hopefully this fix doesn't cause other issues.

PS: This repo could use the magic of pnpm workspaces 😬

### CODE REVIEW

**Comment by PuruVJ** [comment]
Thanks for this buddy! Lemme quickly test it

PS: WDYM about workspaces? 😅

**Comment by bluwy** [comment]
> WDYM about workspaces?

Could have a root `pnpm-workspace.yaml` file so the `demo` app is installed together, and the demo app can reference `svelte-drag` as `workspace:*` so it runs the local copy.

Or the `demo` app can reference `svelte-drag` as `link:../`, just a small nice-to-have.

Downside of `pnpm-workspace.yaml` though is if you're installing new modules in the root, you need the `-W` flag.

**Comment by PuruVJ** [comment]
I actually tried that before. But was confused whethr the main package should be moved to its own folder or not

Can pnpm workspace include root directory as whole package and a folder inside it as another?

**Comment by PuruVJ** [comment]
BTW, let's move to discord. This PR works, so gonna merge it. Again, thanks for this. Yur awesome 🔥

**Pull request merged**
